const skills = [
    { name : ".NET" , short : "net"},
    { name : "Alibaba Cloud" , short : "ali"},
    { name : "Angular" , short : "ang"},
    { name : "Ansible" , short : "ans"},
    { name : "ASP .NET Core" , short : "asp"},
    { name : "AWS" , short : "aws"},
    { name : "AWS CDK" , short : "cdk"},
    { name : "AWS Lambda" , short : "lam"},
    { name : "Azure" , short : "azr"},
    { name : "Bash" , short : "bas"},
    { name : "BitBucket" , short : "bit"},
    { name : "Blackchain Development" , short : "bch"},
    { name : "Bootstrap" , short : "bst"},
    { name : "C" , short : "c"},
    { name : "C#" , short : "csh"},
    { name : "C++" , short : "cpp"},
    { name : "Cassandra" , short : "cas"},
    { name : "Cloudflare" , short : "clf"},
    { name : "Cloudformation" , short : "cfn"},
    { name : "Cobra" , short : "cob"},
    { name : "COBOL" , short : "cbl"},
    { name : "Computer Vision" , short : "cvn"},
    { name : "Convolutional Neural Networks" , short : "cnn"},
    { name : "CouchDB" , short : "cou"},
    { name : "CSS" , short : "css"},
    { name : "Curl" , short : "cur"},
    { name : "Data Analysis" , short : "dan"},
    { name : "Data Structures And Algorithms" , short : "dsa"},
    { name : "Dart" , short : "dar"},
    { name : "Deep Learning" , short : "dln"},
    { name : "DevOps" , short : "dvo"},
    { name : "Digital Ocean" , short : "doc"},
    { name : "Django" , short : "dja"},
    { name : "Docker" , short : "doc"},
    { name : "EDA" , short : "eda"},
    { name : "Enther.js" , short : "eth"},
    { name : "Express JS" , short : "exp"},
    { name : "Firebase" , short : "fbs"},
    { name : "Flask" , short : "flk"},
    { name : "Flutter" , short : "flt"},
    { name : "Fortran" , short : "frt"},
    { name : "Foundry" , short : "fnd"},
    { name : "GIT" , short : "git"},
    { name : "Github" , short : "ghb"},
    { name : "Gitlab" , short : "gla"},
    { name : "GraphQL" , short : "gra"},
    { name : "Go" , short : "go"},
    { name : "Google Cloud" , short : "gcl"},
    { name : "gRPC" , short : "grp"},
    { name : "Heroku" , short : "her"},
    { name : "HTML" , short : "htm"},
    { name : "IaaS" , short : "iaa"},
    { name : "InfluxDB" , short : "inf"},
    { name : "Java" , short : "jav"},
    { name : "Javascript" , short : "jvs"},
    { name : "JSON API" , short : "jso"},
    { name : "JWT" , short : "jwt"},
    { name : "Kafka" , short : "kfk"},
    { name : "Kite" , short : "kit"},
    { name : "Kotlin" , short : "kot"},
    { name : "Kubernates" , short : "kbs"},
    { name : "Linode" , short : "lin"},
    { name : "LSTM" , short : "lsm"},
    { name : "Netlify" , short : "ntf"},
    { name : "Neo4j" , short : "neo"},
    { name : "Next JS" , short : "nxt"},
    { name : "Node JS" , short : "nod"},
    { name : "Neural Networks" , short : "nnw"},
    { name : "NLP" , short : "nlp"},
    { name : "Nuxt JS" , short : "nux"},
    { name : "Machine Learning" , short : "mln"},
    { name : "MariaDB" , short : "mdb"},
    { name : "MLOps" , short : "mlo"},
    { name : "MongoDB" , short : "mdb"},
    { name : "MS SQL" , short : "msq"},
    { name : "MySQL" , short : "mys"},
    { name : "OAuth" , short : "oau"},
    { name : "Orcale" , short : "ora"},
    { name : "Oz" , short : "oz"},
    { name : "PaaS" , short : "pas"},
    { name : "Pascal" , short : "pas"},
    { name : "Perl" , short : "per"},
    { name : "PHP" , short : "php"},
    { name : "PostCSS" , short : "pcs"},
    { name : "PostgreSQL" , short : "pgs"},
    { name : "Python" , short : "pyt"},
    { name : "Quantum Computing" , short : "qcm"},
    { name : "Qwik" , short : "qwk"},
    { name : "R" , short : "r"},
    { name : "RabitMQ" , short : "rbm"},
    { name : "Radix UI" , short : "rui"},
    { name : "React" , short : "rct"},
    { name : "React Native" , short : "rnt"},
    { name : "Recurrent neural network" , short : "rnn"},
    { name : "Redis" , short : "rds"},
    { name : "Remix" , short : "rmx"},
    { name : "REST API" , short : "res"},
    { name : "RethinkDB" , short : "rtd"},
    { name : "Ruby" , short : "rby"},
    { name : "Rust" , short : "rst"},
    { name : "SASS" , short : "sas"},
    { name : "Scala" , short : "sca"},
    { name : "Selenium" , short : "sel"},
    { name : "SOAP API" , short : "soa"},
    { name : "Solid JS" , short : "sol"},
    { name : "Solidity" , short : "sol"},
    { name : "Spring Boot" , short : "spb"},
    { name : "SQLite" , short : "sql"},
    { name : "Svelte" , short : "svt"},
    { name : "Svelte Kit" , short : "svk"},
    { name : "Swift" , short : "swf"},
    { name : "System Design" , short : "sys"},
    { name : "Tailwind" , short : "twd"},
    { name : "Tauri" , short : "tur"},
    { name : "Terraform" , short : "trm"},
    { name : "TimeScale" , short : "tsc"},
    { name : "Tranformers" , short : "trf"},
    { name : "Truffle" , short : "tru"},
    { name : "Typescript" , short : "typ"},
    { name : "Vercel" , short : "vcl"},
    { name : "VirtualBox" , short : "vbx"},
    { name : "VMWare" , short : "vmw"},
    { name : "Vue.js" , short : "vue"},
    { name : "Vultr" , short : "vlt"},
    { name : "Vyper" , short : "vyp"},
    { name : "Web-Sockets" , short : "wsk"},
    { name : "Web3.js" , short : "wjs"},
    { name : "Wordpress" , short : "wrd"},
    { name : "XHTML" , short : "xht"},
    { name : "XML" , short : "xml"},
];

export {skills};